# Game Engine

This suite of applications are the following:

* Game Engine using the C++ application.
* GUI mode to handle game CRUD operations.

Using this applications using C++ and C# to work on fundations
using both languages like C++ and C#. Version of C++ will be
higher than the C++11, and .NET application is going to be
written using the .NET 8.0 version either.

= 1 Introduction
:toc:

== 1.1. Preambles

I am doing this project to learn about both C# (ASP.NET) and C++
by making use of Visual Studio 2022 for the entire solution
(that is about to be the .sln file that contains both Engine in
C++ and the GUI in ASP.NET).

Even though it is a project I am doing on my own, I don't think
that the project is going to be done quickly. This way the fact
of making use of the Git's branching will be needed. Just to say
it once, the application I am designing (both Editor and the
Engine are named "Primal")

== 1.2. Primal Engine

The Engine is about to be written using the C++ language, the
C++ application contains a lot of features that allows user of
it to handle a lot of things like memory management or graphics
randering.

== 1.3. Primal Editor

The editor of the Primal solution is written using C# and XAML
by making use of ASP.NET and Visual Studio features to handle
both C# classes and XAML configuration files.

